accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegister.as_view(), name='register'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('dashboard/', views.UserDashboard.as_view(), name='dashboard'),
    path('api/', include('accounts.api_urls', namespace='jwt')),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('o/', include('social_django.urls', namespace='social')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('core.urls', namespace='core')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from . import views


app_name = 'core'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('question/', views.Question.as_view(), name='question'),
    path('api/', include('core.api_urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.db import models
from .managers import CustomUserManager


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(max_length=100, unique=True, blank=True, null=True)
    password = models.CharField(max_length=255)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    avatar = models.ImageField(upload_to='users/profile/', blank=True, null=True)
    modify_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []
    objects = CustomUserManager()

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

    def __str__(self):
        return self.username

    def save(self, *args, **kwargs):
        if self.is_superuser:
            self.is_staff = True
        return super().save(*args, **kwargs)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.text import slugify


USER = get_user_model()

class Question(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE, related_name='questions')
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=210, unique=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'question'
        verbose_name_plural = 'questions'

    def __str__(self):
        return f'{self.title}'

    def generate_slug(self, title):
        return slugify(title, allow_unicode=True)

    def save(self, *args, **kwargs):
        self.slug = self.generate_slug(self.title)
        return super().save(*args, **kwargs)


class Answer(models.Model):
    user = models.ForeignKey(USER, on_delete=models.CASCADE, related_name='answers')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='answers')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    last_edit = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'answer'
        verbose_name_plural = 'answers'

    def __str__(self):
        return f'{self.user}-{self.question}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    """this form for custom user"""
    class Meta:
        model = CustomUser
        fields = ('email', 'is_superuser',)


class CustomUserChangeForm(UserChangeForm):
    """this form for custom user"""
    class Meta:
        model = CustomUser
        fields = (
            'email',
            'is_superuser',
            )


class UserRegistrationForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control'}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control'}
        )
    )



class UserLoginForm(forms.Form):
    """this is custom form for LoginView"""
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class':'form-control'}
            )
        )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class':'form-control'}
            )
        )
        

class UserAvatarForm(forms.Form):
    """update user avatar"""
    avatar = forms.ImageField(
            widget=forms.FileInput(
                attrs={'class': 'btn btn-info'}
                )
            )

accounts/views.py
from django.views.generic import FormView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_view, login, authenticate
from django.urls import reverse_lazy
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth import get_user_model
from .models import CustomUser
from . import forms
from permissions.permissions import IsNotAuthenticated


class UserRegister(IsNotAuthenticated, FormView):
    model = CustomUser
    form_class = forms.UserRegistrationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('accounts:dashboard')

    def form_valid(self, form):
        cd = form.cleaned_data
        user = CustomUser.objects.create_user(
            username=cd['username'],
            email=cd['email'],
            password=cd['password'],
        )
        return super().form_valid(form)


class UserLogin(IsNotAuthenticated, FormView):
    form_class = forms.UserLoginForm
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('core:home')

    def form_valid(self, form):
        cd = form.cleaned_data
        try:
            user = authenticate(self.request, username=cd['username'], password=cd['password'])
            login(self.request, user)
            messages.success(self.request, 'you logged in successfuly', 'info')
        except:
            messages.success(self.request, 'username or password worng', 'danger')
            return render(self.request, self.template_name, {'form': self.form_class})
        return super().form_valid(form)


class UserLogout(LoginRequiredMixin, auth_view.LogoutView):
    next_page = 'accounts:login'


class UserDashboard(LoginRequiredMixin, FormView, ListView):
    USER = get_user_model()
    template_name = 'accounts/dashboard.html'
    context_object_name = 'user'
    form_class = forms.UserAvatarForm
    success_url = reverse_lazy('accounts:dashboard')

    def get_queryset(self):
        user = self.USER.objects.get(username=self.request.user)
        return user
    
    # update user avatar
    def post(self, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            cd = form.cleaned_data
            user = self.USER.objects.get(username=self.request.user)
            user.avatar = cd['avatar']
            user.save()
            messages.success(self.request, 'your avatar update', 'success')
        return super().form_valid(form)

core/views.py
from django.views import generic
from django.shortcuts import render
from permissions.permissions import QuestionGroupMixin
from . import models


class Home(generic.View):
    def get(self, request):
        return render(request, 'core/home.html')


class Question(QuestionGroupMixin, generic.ListView):
    model = models.Question
    context_object_name = 'questions'
    template_name = 'core/question.html'

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content%}


<h2 class="text-center">{{ user }}</h2>
{% if user.avatar %}
<img class="rounded mx-auto d-block" src="{{ user.avatar.url }}" alt="{{ user }}" style="width:200px; height:200px">
{% endif %}
<p>{{ user.email }}</p>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="update">
</form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content%}
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}


{% block content%}
<form method="post">
{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register">
</form>
<br>
<a href="{% url 'social:begin' 'github' %}" class="btn btn-info">GitHub</a>
{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}

{% block content %}
<h3>home</h3>

{% endblock %}

core/templates/core/question.html
{% extends 'base.html' %}

{% block content %}
<h3>Questions</h3>
<br>
{% for question in questions %}
<div class="col-md-12">
<p>user: {{ question.user }}</p>
<p>title: {{ question.title }}</p>
</div>
<hr>
{% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% include "inc/navbar.html"%}
    <div class="jumbotron">
        {% include "inc/messages.html" %}
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    {% block js_file %}{% endblock %}
</body>

</html>

templates/inc/messages.html
{% if messages %}

    {% for message in messages %}
        <p {% if message.tags %} class='alert alert-{{ message.tags }}' {% endif %}>
            {{ message }}
        </p>
    {% endfor %}

{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a class="nav-link" href="{% url 'core:home' %}">Home</a>
        <a class="nav-link" href="{% url 'core:question' %}">Questions</a>
        {% if not request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        {% else %}
        <a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard</a>
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
        {% endif %}
    </div>
    </div>
</nav>